name: CI CD

on:
  push:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 17.x
      uses: actions/setup-node@v1
      with:
        node-version: 17.x
        cache: 'yarn'

    - name: Build
      run: |
        yarn install
        yarn build

    - name: Prettier
      run: yarn prettier
      
    - name: 📂 Deploy files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: melinakrzemowa.pl
        username: deploy@melinakrzemowa.pl
        password: ${{ secrets.ftp_password }}
        local-dir: ./dist/
        server-dir: /mooncraft/
